server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    url: jdbc:postgresql:///gdrive
    username: postgres
    password: sBCA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

GOOGLE_CLIENT_ID: 860610313465-b4neiok3q9k9fanud119db2g9to0ai59.apps.googleusercontent.com
GOOGLE_SECRET: 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