import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/app/_component/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#000100] text-[#E8E9ED]`}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}

/*
4C4C4C=>light
999799==> for ligth bg
FFFFFF==>font gray

 */
