import "./globals.css";
import { Roboto } from "next/font/google";
import NavBar from "@/app/_component/NavBar";
import type { Metadata } from "next";

const inter = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#0b0a07] text-[#E8E9ED]`}>
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  );
}

/*
4C4C4C=>light
999799==> for ligth bg
FFFFFF==>font gray

 */
